name: Print Temperature
on:
  workflow_dispatch:
    inputs:
      temperature:
        description: 'La tempÃ©rature reÃ§ue depuis Airflow'
        required: true

jobs:
  print_temperature:
    runs-on: ubuntu-latest
    steps:
      - name: Affichage de la donnÃ©e
        run: |
          echo "ğŸŒ¡ï¸ ALERTE MÃ‰TÃ‰O RECUE !"
          echo "La tempÃ©rature actuelle Ã  Paris est de ${{ github.event.inputs.temperature }} Kelvin"
